### index

GET http://localhost:3000/products

### show
GET http://localhost:3000/products/7

### create
Post http://localhost:3000/products
Content-Type: application/json

{
    "name": "Iphone",
    "price": "test",
    "image_url": "test",
    "description": "test"
}

### updates
PATCH http://localhost:3000/products/9
Content-Type: application/json

{
    "name": "Iphone",
    "price": "test",
    "image_url": "testing",
    "decription": "test"
}

### destroy
DELETE  http://localhost:3000/products/7
